version: '3'

services:
  db:
      container_name: django_db
      image: mysql
      environment:
          - MYSQL_DATABASE=core
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=passwd
      networks:
        - core
      ports:
         - 33069:3306

  core:
      build: python
      container_name: django_core
      command: python3 manage.py runserver 0.0.0.0:8000
      networks:
        - core
      volumes:
          - ./python:/var/www
      ports:
        - "8000:8000"

networks:
    core: